# Generated by Django 3.1.2 on 2021-08-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brends',
            field=models.CharField(choices=[('1 brend', '1 brend'), ('2 brend', '2 brend'), ('3 brend', '3 brend')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
