# Generated by Django 3.1.2 on 2021-08-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210815_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(null=True, to='store.Color'),
        ),
    ]
